version: "3.4"

services:
  app:
    build:
      context: ../
      dockerfile: writer/infrastructure/docker/Dockerfile
      target: archive
    volumes: 
        - ./:/code
    ports:
      - "1010:8080"
