version: "3.4"

services:
  maven:
    build:
        context: ../
        dockerfile: writer/docker/Dockerfile
    volumes: 
        - ./:/code
    working_dir: /code
  tomcat:
    build:
      context: ../
      dockerfile: writer/docker/Dockerfile
    volumes: 
        - ./:/code
    ports:
      - "8080:8080"
